apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
  namespace: jjennings
  labels:
    app: db
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  minReadySeconds: 20
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - envFrom:
        - secretRef:
            name: db-secret
        name: db-deployment
        image: harbor.dev.afsmtddso.com/jjennings-harbor-project/db:439ddf5-a7ffbb6
        ports: 
        - containerPort: 5432
